// Decompiled with JetBrains decompiler
// Type: MSXML2._SCHEMADERIVATIONMETHOD
// Assembly: Interop.MSXML2, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 42FF73EE-2D3B-484F-8393-2D9B139D2D95
// Assembly location: C:\Program Files (x86)\Sam Accounting Services\Module7\Interop.MSXML2.dll

#nullable disable
namespace MSXML2;

public enum _SCHEMADERIVATIONMETHOD
{
  SCHEMADERIVATIONMETHOD_EMPTY = 0,
  SCHEMADERIVATIONMETHOD_SUBSTITUTION = 1,
  SCHEMADERIVATIONMETHOD_EXTENSION = 2,
  SCHEMADERIVATIONMETHOD_RESTRICTION = 4,
  SCHEMADERIVATIONMETHOD_LIST = 8,
  SCHEMADERIVATIONMETHOD_UNION = 16, // 0x00000010
  SCHEMADERIVATIONMETHOD_ALL = 255, // 0x000000FF
  SCHEMADERIVATIONMETHOD_NONE = 256, // 0x00000100
}
